### ISSUE TITLE
Hide all status when not connected

### ISSUE THREAD

**Issue by timtyrrell** [tardunge/kmux-status#2]
Is there a way to not show the `#{kcontext}` unless you are actually connected?

**Comment by tardunge** [comment]
Actually, the script doesn't connect to any kubernetes cluster. It retrieves the information from processes running on host and kubeconfig file. Also, there wont be any connection process running to know the connection status. When you execute kubectl command it communicates to kubernetes over http call.
Closing this as this can't be achieved.
